# Generated by Django 4.1.4 on 2023-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.CharField(max_length=100)),
                ('question', models.ManyToManyField(to='PQ.question')),
            ],
            options={
                'ordering': ['why'],
            },
        ),
        migrations.CreateModel(
            name='Who',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=100)),
                ('question', models.ManyToManyField(to='PQ.question')),
            ],
            options={
                'ordering': ['who'],
            },
        ),
        migrations.CreateModel(
            name='When',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.CharField(max_length=100)),
                ('question', models.ManyToManyField(to='PQ.question')),
            ],
            options={
                'ordering': ['when'],
            },
        ),
    ]
