# Generated by Django 4.1.4 on 2023-03-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0002_why_who_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='question',
        ),
        migrations.RemoveField(
            model_name='when',
            name='question',
        ),
        migrations.RemoveField(
            model_name='who',
            name='question',
        ),
        migrations.RemoveField(
            model_name='why',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ManyToManyField(to='PQ.type'),
        ),
        migrations.AddField(
            model_name='question',
            name='when',
            field=models.ManyToManyField(to='PQ.when'),
        ),
        migrations.AddField(
            model_name='question',
            name='who',
            field=models.ManyToManyField(to='PQ.who'),
        ),
        migrations.AddField(
            model_name='question',
            name='why',
            field=models.ManyToManyField(to='PQ.why'),
        ),
    ]
