# Generated by Django 4.1.4 on 2023-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0003_remove_type_question_remove_when_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='typeq', to='PQ.type'),
        ),
        migrations.AlterField(
            model_name='question',
            name='when',
            field=models.ManyToManyField(blank=True, related_name='whenq', to='PQ.when'),
        ),
        migrations.AlterField(
            model_name='question',
            name='who',
            field=models.ManyToManyField(blank=True, related_name='whoq', to='PQ.who'),
        ),
        migrations.AlterField(
            model_name='question',
            name='why',
            field=models.ManyToManyField(blank=True, related_name='whyq', to='PQ.why'),
        ),
    ]
