# Generated by Django 4.1.4 on 2023-03-12 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0004_alter_question_type_alter_question_when_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
