# Generated by Django 4.1.4 on 2023-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0006_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='typeset', to='PQ.type'),
        ),
        migrations.AddField(
            model_name='set',
            name='when',
            field=models.ManyToManyField(blank=True, related_name='wheset', to='PQ.when'),
        ),
        migrations.AddField(
            model_name='set',
            name='who',
            field=models.ManyToManyField(blank=True, related_name='whoset', to='PQ.who'),
        ),
        migrations.AddField(
            model_name='set',
            name='why',
            field=models.ManyToManyField(blank=True, related_name='whyset', to='PQ.why'),
        ),
    ]
