# Generated by Django 4.1.4 on 2023-03-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0007_set_type_set_when_set_who_set_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='questions',
            field=models.ManyToManyField(null=True, related_name='questions_set', to='PQ.question'),
        ),
    ]
