# Generated by Django 4.1.4 on 2023-03-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0009_alter_question_dateadded_alter_set_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['dategenerated']},
        ),
    ]
