# Generated by Django 4.1.4 on 2023-03-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0010_alter_set_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={},
        ),
    ]
