# Generated by Django 4.1.4 on 2023-03-15 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0011_alter_set_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='type',
        ),
        migrations.RemoveField(
            model_name='set',
            name='when',
        ),
        migrations.RemoveField(
            model_name='set',
            name='who',
        ),
        migrations.RemoveField(
            model_name='set',
            name='why',
        ),
        migrations.AddField(
            model_name='set',
            name='type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='typeset', to='PQ.type', verbose_name='types of questions you look for'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='when',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wheset', to='PQ.when', verbose_name='when you want to use them'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='who',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whoset', to='PQ.who', verbose_name='who you want to ask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='why',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='whyset', to='PQ.why', verbose_name='why you want to ask them'),
            preserve_default=False,
        ),
    ]
