# Generated by Django 4.1.4 on 2023-03-15 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0012_remove_set_type_remove_set_when_remove_set_who_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeset', to='PQ.type', verbose_name='types of questions you look for'),
        ),
    ]
