# Generated by Django 4.1.4 on 2023-03-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0013_alter_set_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='when',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheset', to='PQ.when', verbose_name='when you want to use them'),
        ),
        migrations.AlterField(
            model_name='set',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whoset', to='PQ.who', verbose_name='who you want to ask'),
        ),
        migrations.AlterField(
            model_name='set',
            name='why',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whyset', to='PQ.why', verbose_name='why you want to ask them'),
        ),
    ]
