# Generated by Django 4.1.4 on 2023-03-15 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0014_alter_set_when_alter_set_who_alter_set_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeset', to='PQ.type', verbose_name='types of questions'),
        ),
    ]
