# Generated by Django 4.1.4 on 2023-03-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0017_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='firsttime',
            field=models.BooleanField(default=True),
        ),
    ]
