# Generated by Django 4.1.4 on 2023-03-19 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0019_proposedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposedquestion',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_question', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
