# Generated by Django 4.1.4 on 2023-03-19 21:25

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0022_proposedquestion_pset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halloffame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('twitter', models.URLField(max_length=1000)),
                ('linkedin', models.URLField(max_length=1000)),
                ('facebook', models.URLField(max_length=1000)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('questions', models.ManyToManyField(related_name='halloffame_questions', to='PQ.question')),
            ],
        ),
    ]
