# Generated by Django 4.1.4 on 2023-03-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0023_halloffame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffame',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
