# Generated by Django 4.1.4 on 2023-03-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0024_alter_halloffame_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffame',
            name='facebook',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='linkedin',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='halloffame',
            name='twitter',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
