# Generated by Django 4.1.4 on 2023-03-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0026_alter_halloffame_facebook_alter_halloffame_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halloffame',
            name='questions',
        ),
        migrations.AddField(
            model_name='halloffame',
            name='question1',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halloffame',
            name='question2',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halloffame',
            name='question3',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halloffame',
            name='question4',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='halloffame',
            name='question5',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
