# Generated by Django 4.1.4 on 2023-03-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0027_remove_halloffame_questions_halloffame_question1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffame',
            name='photo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
