# Generated by Django 4.1.4 on 2023-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0028_alter_halloffame_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='halloffame',
            name='website',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
