# Generated by Django 4.1.4 on 2023-03-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PQ', '0029_halloffame_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='halloffame',
            old_name='question4',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='halloffame',
            name='question5',
        ),
    ]
